'use strict';

module.exports = {
  adhocFlowOverview: (invoke) => (payload) => invoke('adhocFlow:overview', payload || {}),
  adhocFlowRun: (invoke) => (payload) => invoke('adhocFlow:run', payload || {}),
  adhocFlowInteractionResponse: (invoke) => (payload) => invoke('adhocFlow:interactionResponse', payload || {}),
  adhocFlowSubmit: (invoke) => (payload) => invoke('adhocFlow:submit', payload || {}),
  adhocFlowResubmit: (invoke) => (payload) => invoke('adhocFlow:resubmit', payload || {}),
  adhocFlowCancel: (invoke) => (payload) => invoke('adhocFlow:cancel', payload || {}),
  adhocFlowForceComplete: (invoke) => (payload) => invoke('adhocFlow:forceComplete', payload || {}),
  adhocFlowDeleteRun: (invoke) => (payload) => invoke('adhocFlow:deleteRun', payload || {}),
  adhocFlowSavePreset: (invoke) => (payload) => invoke('adhocFlow:savePreset', payload || {}),
  adhocFlowDeletePreset: (invoke) => (payload) => invoke('adhocFlow:deletePreset', payload || {}),
  adhocFlowSaveWorkflow: (invoke) => (payload) => invoke('adhocFlow:saveWorkflow', payload || {}),
  adhocFlowDeleteWorkflow: (invoke) => (payload) => invoke('adhocFlow:deleteWorkflow', payload || {}),
  adhocFlowCopyMethod: (invoke) => (payload) => invoke('adhocFlow:copyMethod', payload || {}),
  adhocFlowSnapshotSelection: (invoke) => (payload) => invoke('adhocFlow:snapshotSelection', payload || {}),
  adhocFlowDesignPreview: (invoke) => (payload) => invoke('adhocFlow:designPreview', payload || {}),
  adhocFlowExecutionPreview: (invoke) => (payload) => invoke('adhocFlow:executionPreview', payload || {}),
  adhocFlowPromote: (invoke) => (payload) => invoke('adhocFlow:promote', payload || {}),
  adhocFlowSaveSettings: (invoke) => (payload) => invoke('adhocFlow:saveSettings', payload || {}),
  designSessionList: (invoke) => (payload) => invoke('designSession:list', payload || {}),
  designSessionGet: (invoke) => (payload) => invoke('designSession:get', payload || {}),
  designSessionStart: (invoke) => (payload) => invoke('designSession:start', payload || {}),
  designSessionDelete: (invoke) => (payload) => invoke('designSession:delete', payload || {}),
  workflowTaskList: (invoke) => () => invoke('workflowTask:list', {}),
  workflowTaskCreate: (invoke) => (payload) => invoke('workflowTask:create', payload || {}),
  workflowTaskDelete: (invoke) => (payload) => invoke('workflowTask:delete', payload || {}),
  workflowTaskExecute: (invoke) => (payload) => invoke('workflowTask:execute', payload || {}),
  preparationRecommend: (invoke) => (payload) => invoke('preparation:recommend', payload || {}),
  preparationList: (invoke) => (payload) => invoke('preparation:list', payload || {}),
  preparationGet: (invoke) => (payload) => invoke('preparation:get', payload || {}),
  preparationCreate: (invoke) => (payload) => invoke('preparation:create', payload || {}),
  preparationCreatePackage: (invoke) => (payload) => invoke('preparation:createPackage', payload || {}),
  preparationDelete: (invoke) => (payload) => invoke('preparation:delete', payload || {}),
  preparationStartDesign: (invoke) => (payload) => invoke('preparation:startDesign', payload || {}),
  preparationSyncDesign: (invoke) => (payload) => invoke('preparation:syncDesign', payload || {}),
  preparationCompleteDesign: (invoke) => (payload) => invoke('preparation:completeDesign', payload || {}),
  preparationHandoff: (invoke) => (payload) => invoke('preparation:handoff', payload || {}),
};
