import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Custom plugin that writes the worker code to a temp file and loads it via file:// URL.
// blob: URL workers are blocked by corporate proxy security software.
// worker_threads are unavailable in Electron's renderer process (Chromium V8 platform).
// file:// URL workers bypass proxy restrictions and work in Electron renderer.
function nodeWorkerPlugin() {
  return {
    name: 'node-worker-plugin',
    setup(build) {
      build.onLoad(
        { filter: /\.worker\.(js|jsx|ts|tsx)$/ },
        async ({ path: workerPath }) => {
          const workerCode = await fs.promises.readFile(workerPath, { encoding: 'utf-8' });

          return {
            contents: `
const os = require('os');
const nodePath = require('path');
const nodefs = require('fs');
const { pathToFileURL } = require('url');
const WORKER_CODE = ${JSON.stringify(workerCode)};

let workerFileURL = null;
try {
  const workerFile = nodePath.join(os.tmpdir(), 'obsidian-textlint-worker.js');
  nodefs.writeFileSync(workerFile, WORKER_CODE, 'utf-8');
  workerFileURL = pathToFileURL(workerFile).href;
} catch (e) {
  console.error('[textlint]: failed to write worker file:', e.message);
}

export default function Worker() {
  if (!workerFileURL) {
    throw new Error('[textlint]: Worker file could not be created in temp dir: ' + os.tmpdir());
  }
  return new globalThis.Worker(workerFileURL);
}
`,
            loader: 'js',
          };
        }
      );
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  allowOverwrite: true,
  entryPoints: ['src/main.ts'],
  bundle: true,
  minify: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  plugins: [nodeWorkerPlugin()],
  format: 'cjs',
  target: 'esnext',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
