import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Custom plugin that uses Node.js worker_threads instead of blob URL Web Workers.
// blob: URL workers are blocked by corporate proxy security software, causing the
// worker to fail silently. Node.js worker_threads bypasses this restriction entirely.
function nodeWorkerPlugin() {
  return {
    name: 'node-worker-plugin',
    setup(build) {
      build.onLoad(
        { filter: /\.worker\.(js|jsx|ts|tsx)$/ },
        async ({ path: workerPath }) => {
          const workerCode = await fs.promises.readFile(workerPath, { encoding: 'utf-8' });

          // Shim that maps Web Worker globals (self, postMessage, addEventListener)
          // to the Node.js worker_threads equivalents (parentPort).
          const shimLines = [
            'const { parentPort } = require("worker_threads");',
            'const self = {',
            '  postMessage: function(data) { parentPort.postMessage(data); },',
            '  addEventListener: function(type, handler) {',
            '    if (type === "message") {',
            '      parentPort.on("message", function(data) { handler({ data: data }); });',
            '    } else if (type === "error") {',
            '      process.on("uncaughtException", function(err) {',
            '        handler({ error: err, message: err.message || String(err), preventDefault: function() {} });',
            '      });',
            '    } else if (type === "unhandledrejection") {',
            '      process.on("unhandledRejection", function(reason) {',
            '        handler({ reason: reason, preventDefault: function() {} });',
            '      });',
            '    }',
            '  },',
            '  removeEventListener: function() {}',
            '};',
            'Object.defineProperty(globalThis, "self", { value: self, configurable: true, writable: true });',
          ];
          const shim = shimLines.join('\n');

          return {
            contents: `
const { Worker: NodeWorker } = require('worker_threads');
const WORKER_CODE = ${JSON.stringify(shim + '\n' + workerCode)};

export default function Worker() {
  const nodeWorker = new NodeWorker(WORKER_CODE, { eval: true });
  const pending = [];
  let handler = null;

  nodeWorker.on('message', function(data) {
    if (handler) {
      handler({ data: data });
    } else {
      pending.push(data);
    }
  });

  return {
    postMessage: function(msg) { nodeWorker.postMessage(msg); },
    get onmessage() { return handler; },
    set onmessage(fn) {
      handler = fn;
      while (pending.length) handler({ data: pending.shift() });
    },
    terminate: function() { return nodeWorker.terminate(); }
  };
}
`,
            loader: 'js',
          };
        }
      );
    },
  };
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  allowOverwrite: true,
  entryPoints: ['src/main.ts'],
  bundle: true,
  minify: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  plugins: [nodeWorkerPlugin()],
  format: 'cjs',
  target: 'esnext',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
