'use strict';

const { contextBridge, ipcRenderer } = require('electron');

async function invoke(channel, args) {
  const res = await ipcRenderer.invoke(channel, args);
  if (!res || !res.ok) throw new Error(res && res.error ? res.error : `${channel} が失敗しました`);
  return res.data;
}

const on = (channel) => (cb) => ipcRenderer.on(channel, (_ev, p) => cb(p));

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  hostInfo: () => invoke('host:info'),
  getConfig: () => invoke('config:get'),
  saveConfig: (patch) => invoke('config:save', { patch }),
  addRepo: () => invoke('repo:add'),
  removeRepo: (repo) => invoke('repo:remove', { repo }),
  listAgents: (repo) => invoke('agents:list', { repo }),
  listSessions: (repo) => invoke('session:list', { repo }),
  createSession: (payload) => invoke('session:create', payload),
  readSession: (id) => invoke('session:read', { id }),
  updateSession: (id, patch) => invoke('session:update', { id, patch }),
  removeSession: (id) => invoke('session:remove', { id }),
  // opts: { cli, model, readonly, attachments: [{ id, name } | { rel, name }] } — ターンごとに変えられる
  send: (id, prompt, opts) => invoke('turn:send', { id, prompt, ...(opts || {}) }),
  pickAttachments: () => invoke('attach:pick'),
  stageAttachment: (name, bytes) => invoke('attach:stage', { name, bytes }),
  discardAttachment: (id) => invoke('attach:discard', { id }),
  openAttachment: (id, name) => invoke('attach:open', { id, name }),
  stop: (id) => invoke('turn:stop', { id }),
  running: () => invoke('turn:running'),
  termOpen: (id, cols, rows) => invoke('term:open', { id, cols, rows }),
  termRestart: (id, cols, rows) => invoke('term:restart', { id, cols, rows }),
  termState: (id) => invoke('term:state', { id }),
  termWatch: (id) => invoke('term:watch', { id }),
  termUnwatch: (id) => invoke('term:unwatch', { id }),
  termKeys: (id, data) => invoke('term:keys', { id, data }),
  termResize: (id, cols, rows) => invoke('term:resize', { id, cols, rows }),
  termKill: (id) => invoke('term:kill', { id }),
  listWorktrees: (repo) => invoke('wt:list', { repo }),
  createWorktree: (repo, branch, base, name) => invoke('wt:create', { repo, branch, base, name }),
  removeWorktree: (repo, name, opts) => invoke('wt:remove', { repo, name, ...(opts || {}) }),
  listDir: (repo, worktree, rel) => invoke('fs:list', { repo, worktree, rel }),
  readFile: (repo, worktree, rel) => invoke('fs:read', { repo, worktree, rel }),
  findFiles: (repo, worktree, query) => invoke('fs:find', { repo, worktree, query }),
  changes: (repo, worktree, scope) => invoke('git:changes', { repo, worktree, scope }),
  fileDiff: (repo, worktree, file, scope) => invoke('git:file', { repo, worktree, file, scope }),
  openFolder: (repo, worktree) => invoke('shell:openFolder', { repo, worktree }),
  openFile: (repo, worktree, rel) => invoke('shell:openFile', { repo, worktree, rel }),
  showFile: (repo, worktree, rel) => invoke('shell:showFile', { repo, worktree, rel }),
  automation: {
    getConfig: () => invoke('automation:config:get'),
    saveConfig: (config) => invoke('automation:config:save', { config }),
    catalog: () => invoke('automation:catalog:get'),
    addRoot: () => invoke('automation:root:add'),
    removeRoot: (root) => invoke('automation:root:remove', { root }),
    selectRoot: (root) => invoke('automation:root:select', { root }),
    listMachines: (root) => invoke('automation:machine:list', { root }),
    readMachine: (root, machine) => invoke('automation:machine:read', { root, machine }),
    machineExists: (root, machine) => invoke('automation:machine:exists', { root, machine }),
    previewMachine: (spec) => invoke('automation:machine:preview', { spec }),
    saveMachine: (root, spec) => invoke('automation:machine:save', { root, spec }),
    openMachineFolder: (root, machine) => invoke('automation:machine:openFolder', { root, machine }),
    listAgents: (root) => invoke('automation:agents:list', { root }),
    toolStatus: (root) => invoke('automation:tools:status', { root }),
    recordingStart: (payload) => invoke('automation:recording:start', payload),
    recordingStop: (payload) => invoke('automation:recording:stop', payload),
    recordingImport: (payload) => invoke('automation:recording:import', payload),
    recordingState: () => invoke('automation:recording:state'),
    aiStart: (payload) => invoke('automation:ai:start', payload),
    aiStop: (requestId) => invoke('automation:ai:stop', { requestId }),
    aiApply: (payload) => invoke('automation:ai:apply', payload),
    onAiProgress: on('automation:ai:progress'),
    onAiResult: on('automation:ai:result'),
    runSnapshot: (root) => invoke('automation:run:snapshot', { root }),
    saveRunSchedule: (root, schedule) => invoke('automation:run:schedule', { root, schedule }),
    setRunDaemon: (root, action) => invoke('automation:run:daemon', { root, action }),
    runLog: (root, identity) => invoke('automation:run:log', { root, identity }),
    runStart: (payload) => invoke('automation:run:start', payload),
    runStop: () => invoke('automation:run:stop'),
    onRunLine: on('automation:run:line'),
    onRunExit: on('automation:run:exit'),
  },
  onTurnStarted: on('turn:started'),
  onTurnLine: on('turn:line'),
  onTurnDone: on('turn:done'),
  onTermScreen: on('term:screen'),
  onTermPhase: on('term:phase'),
});
